fixtures:
  repositories:
    apache: "https://github.com/puppetlabs/puppetlabs-apache.git"
    apt:
      repo: "https://github.com/puppetlabs/puppetlabs-apt.git"
      ref: "1.7.0"
    concat:
      repo: "https://github.com/puppetlabs/puppetlabs-concat.git"
      ref: "1.2.0"
    epel: "https://github.com/stahnma/puppet-module-epel.git"
    mysql: "https://github.com/puppetlabs/puppetlabs-mysql.git"
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
  symlinks:
    owncloud: "#{source_dir}"
